config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :albums, only: [:index, :show, :update] do
    collection do
      get :populate, action: :populate
    end
  end

  resources :tags, except: [:show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id               :integer          not null, primary key
#  user_id          :integer
#  spotify_id       :string
#  name             :string
#  image_large_url  :string
#  image_medium_url :string
#  image_small_url  :string
#  href             :string
#  uri              :string
#  artists          :jsonb
#  added_at         :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Album < ActiveRecord::Base
  has_many :tracks, dependent: :destroy
  has_many :tags, through: :album_tags
  has_many :album_tags
  belongs_to :user
end

app/controllers/albums_controller.rb
class AlbumsController < AuthenticatedController
  def index
    if params[:tag_id]
      @tag = current_user.tags.find(params[:tag_id])
      @albums = @tag.albums
      @title = @tag.name
    else
      @albums = current_user.albums
      @title = 'Albums'
    end

    @tags = current_user.tags
  end

  def show
    @album = current_user.albums.find(params[:id])
  end

  def update
    @album = current_user.albums.find(params[:id])
    if @album.update(album_params)
      redirect_to album_path(@album), notice: 'Great job. Success.'
    else
      redirect_to album_path(@album), alert: 'No good. Something went wrong.'
    end
  end

  def populate
    spotify_user = RSpotify::User.new(current_user.auth_hash)

    current_user.albums.destroy_all

    limit = 50
    offset = 0

    RSpotify.raw_response = true

    loop do
      items = JSON.parse(spotify_user.saved_albums(limit: limit, offset: offset).body)['items']

      break if items.empty?

      items.each do |item|
        spotify_album = item['album']
        Album.create!(
          user: current_user,
          spotify_id: spotify_album['id'],
          name: spotify_album['name'],
          artists: spotify_album['artists'].map { |album| album['name'] },
          image_large_url: spotify_album['images'][0]['url'],
          image_medium_url: spotify_album['images'][1]['url'],
          image_small_url: spotify_album['images'][2]['url'],
          href: spotify_album['href'],
          uri: spotify_album['uri'],
          added_at: item['added_at']
        )
      end

      offset = offset + limit
    end

    redirect_to albums_path
  end

  private

  def album_params
    params.require(:album).permit!
  end
end

app/views/albums/index.html.erb
<h1><%= @title %></h1>
<div class="access-token" data-access-token="<%= @access_token %>"></div>

<div class="album-grid">
  <% @albums.each do |album| %>
    <div class="album-grid-item">
      <div class="album-grid-item__image album-image" data-uri="<%= album.uri %>" style="background-image: url('<%= album.image_medium_url %>');"></div>
      <div class="album-grid-item__name"><%= link_to album.name, album_path(album), class: 'album-link' %></div>
      <div class="album-grid-item__artist"><%= album.artists.join(', ') %></div>
    </div>
  <% end %>
</div>

<%= javascript_tag do %>
  Albums.init({
    accessToken: '<%= @access_token %>',
    refreshToken: '<%= @refresh_token %>'
  });
<% end %>

app/views/albums/populate.html.erb
<h1>Populated!</h1>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<div class="flex">
  <div class="album__column">
    <div data-uri="<%= @album.uri %>" class="album-image" style="background-image: url('<%= @album.image_medium_url %>');"></div>
  </div>

  <%= form_for(@album) do |f| %>
    <div class="field">
      <%= f.label :tag_ids, 'Folders', class: 'label' %>
      <%= f.collection_check_boxes :tag_ids, @tags, :id, :name do |b| %>
        <div class="checkbox">
          <%= b.label { b.check_box + b.text } %>
        </div>
      <% end %>
    </div>

    <%= f.submit 'Save', class: 'button' %>
  <% end %>
</div>

<%= javascript_tag do %>
  Albums.init({ accessToken: '<%= @access_token %>'});
<% end %>