config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :albums, only: [:index, :show, :update] do
    collection do
      get :populate, action: :populate
    end
  end

  resources :tags, except: [:show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  name       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  belongs_to :user
  has_many :albums, through: :album_tags
  has_many :album_tags
end

app/controllers/tags_controller.rb
class TagsController < AuthenticatedController
  def index
    @tags = current_user.tags
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user
    @tag.save!
    redirect_to tags_path, notice: 'Folder created. Great job.'
  end

  def edit
    @tag = current_user.tags.find(params[:id])
  end

  def update
    @tag = current_user.tags.find(params[:id])
    @tag.update!(tag_params)
    redirect_to tags_path, notice: 'Folder updated. Great job.'
  end

  def destroy
    @tag = current_user.tags.find(params[:id])
    @tag.destroy
    redirect_to tags_path, notice: 'Folder destroyed. Great job.'
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/edit.html.erb
<h1>Edit Folder</h1>

<%= form_for @tag do |f| %>
  <div class="field">
    <%= f.label :name, class: 'label' %>
    <%= f.text_field :name, class: 'input' %>
  </div>

  <div class="field">
    <%= f.submit 'Save', class: 'button' %>
  </div>
<% end %>

app/views/tags/index.html.erb
<h1>Folders</h1>
<p><%= link_to 'Create Folder', new_tag_path %></p>

<% if @tags.any? %>
  <% @tags.each do |tag| %>
  <p>
    <%= tag.name %> - <%= link_to 'Edit', edit_tag_path(tag) %>
  </p>
  <% end %>
<% else %>
  No folders.
<% end %>

app/views/tags/new.html.erb
<h1>Create Folder</h1>

<%= form_for @tag do |f| %>
  <div class="field">
    <%= f.label :name, class: 'label' %>
    <%= f.text_field :name, class: 'input', autofocus: true %>
  </div>

  <div class="field">
    <%= f.submit 'Save', class: 'button' %>
  </div>
<% end %>