config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :albums, only: [:index, :show, :update] do
    collection do
      get :populate, action: :populate
    end
  end

  resources :tags, except: [:show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotify</title>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>

  <script src="https://sdk.scdn.co/spotify-player.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/authenticated.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotify</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>

  <script src="https://sdk.scdn.co/spotify-player.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>

  <div class="layout layout--sidebar">
    <aside class="sidebar">
      <div>
        <div class="sidebar__title">
          <%= link_to 'Folders', tags_path %>
        </div>

        <%= link_to 'All', albums_path, class: 'sidebar__link' %>
        <% @tags.each do |tag| %>
          <%= link_to tag.name, albums_path(tag_id: tag.id), class: 'sidebar__link' %>
        <% end %>
      </div>

      <div>
        <div class="margin-bottom"><%= link_to 'Refresh', populate_albums_path %></div>
        <div><%= link_to 'Logout', destroy_user_session_path, method: :delete %></div>
      </div>
    </aside>

    <div class="main">
      <% if notice %>
        <div class="notice"><%= notice %></div>
      <% end %>

      <% if alert %>
        <div class="alert"><%= alert %></div>
      <% end %>

      <%= yield %>
    </div>

  </div>
</body>
</html>